# Generated by Django 5.2.7 on 2025-10-17 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_diagnostico_terapia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('ano_escolar', models.CharField(max_length=20)),
                ('transporte_escolar', models.BooleanField(default=False)),
                ('numero_vaga', models.PositiveIntegerField()),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.diagnostico')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.escola')),
            ],
        ),
    ]
