# Generated by Django 5.2.7 on 2025-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_vaga',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
