# Generated by Django 5.2.7 on 2025-11-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_aluno_numero_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='terapia',
            name='sigla',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
