# Generated by Django 5.2.7 on 2025-11-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_diagnostico_sigla_terapia_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapia',
            name='cor',
            field=models.CharField(blank=True, choices=[('primary', 'Azul'), ('success', 'Verde'), ('warning', 'Amarelo'), ('danger', 'Vermelho'), ('info', 'Ciano'), ('secondary', 'Cinza'), ('dark', 'Preto')], default='primary', max_length=20, null=True),
        ),
    ]
