# Generated by Django 5.2.7 on 2025-11-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_terapia_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_escolar',
            field=models.CharField(choices=[('BERÇÁRIO I', 'Berçário I'), ('BERÇÁRIO II', 'Berçário II'), ('MATERNAL I', 'Maternal I'), ('MATERNAL II', 'Maternal II'), ('PRE I', 'Pré I'), ('PRE II', 'Pré II'), ('1ANO', '1º Ano'), ('2ANO', '2º Ano'), ('3ANO', '3º Ano'), ('4ANO', '4º Ano'), ('5ANO', '5º Ano'), ('ND', 'Não Definido')], default='ND', max_length=20),
        ),
    ]
