# Generated by Django 5.2.7 on 2025-11-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_aluno_ano_escolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='numero_vaga',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
