# Generated by Django 5.2.7 on 2025-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_aluno_numero_vaga'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'terapia', 'dia_da_semana'), name='matricula_unica_por_dia'),
        ),
    ]
