# Generated by Django 5.2.7 on 2025-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_matricula_matricula_unica_por_dia'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matricula',
            name='matricula_unica_por_dia',
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'terapia'), name='matricula_unica_por_aluno'),
        ),
    ]
