# Generated by Django 5.2.7 on 2025-11-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_aluno_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('FJ', 'Falta Justificada')], default='P', max_length=2)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('matricula', 'data'), name='registro_unico_por_dia')],
            },
        ),
    ]
