# Generated by Django 5.2.7 on 2025-11-17 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terapia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='terapia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.terapia'),
        ),
    ]
