# Generated by Django 5.2.7 on 2025-11-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_diagnostico_ativo_escola_ativo_terapia_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.diagnostico'),
        ),
    ]
