# Generated by Django 5.2.7 on 2025-11-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_diagnostico_nome_alter_escola_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
